- name: Open  VM Port
  hosts: web
  connection: local
  vars_files:
    - var.yml
  tasks:
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ group_name }}"
      name: table4ds1secgroup
      rules:
        - name: apache
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound
