---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource
      azure_rm_resourcegroup:
        name: table4dstest
        location: southeastasia
        tags:
          testing: testing
          delete: never
