- name: Create  VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: table4ds1
      location: southeastasia
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: table4ds1
      name: table4ds1Vnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: table4ds1
      name: table4ds1Subnet
      address_prefix: "10.0.1.0/24"
      virtual_network: table4ds1Vnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: table4ds1
      allocation_method: Static
      name: table4ds1publicIP
    register: output_ip_address
  - name: table4ds1PublicIP
    debug:
      msg: "Public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: table4ds1
      name: table4ds1Securitygroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: table4ds1
      name: table4ds1Nic
      virtual_network: table4ds1Vnet
      subnet: table4ds1Subnet
      public_ip_name: table4ds1PublicIP
      security_group: table4ds1Securitygroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: table4ds1
      name: table4ds1VM
      vm_size: Standard_DS1_v2
      admin_username: azureops
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureops/.ssh/authorized_keys
          key_data: |
           {{ lookup('file','/home/azureops/.ssh/id_rsa.pub') }}
      network_interfaces: table4ds1Nic
      image:
        offer: Ubuntuserver
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
