---
- hosts: localhost
  connection: local
  vars: 
   group: tabl4ds1
   webapp_name: table4ds1webapp
   location: southeastasia
  tasks:
  - name: create rg
    azure_rm_resourcegroup:
     name: "{{group}}"
     location: "{{location}}"
  - name: Create App Svc
    azure_rm_webapp:
      resource_group: "{{group}}"
      name: "{{webapp_name}}"
      plan:
        resource_group: "{{group}}"
        name: table4ds1appplan
        is_linux: true
        sku: S1
        number_of_workers: 1
      frameworks:
         - name: "java"
           version: "8"
           settings:
             java_container: "Tomcat"
             java_container_version: "8.5"

